export enum Permissions {
  // User permissions
  READ_USERS = 'admin:edit',
  CREATE_USERS = 'CREATE_USERS',
  UPDATE_USERS = 'UPDATE_USERS',
  DELETE_USERS = 'DELETE_USERS',

  // Role permissions
  READ_ROLES = 'READ_ROLES',
  CREATE_ROLES = 'CREATE_ROLES',
  UPDATE_ROLES = 'UPDATE_ROLES',
  DELETE_ROLES = 'DELETE_ROLES',

  // Permission permissions
  READ_PERMISSIONS = 'READ_PERMISSIONS',
  CREATE_PERMISSIONS = 'CREATE_PERMISSIONS',
  UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS',
  DELETE_PERMISSIONS = 'DELETE_PERMISSIONS',

  // Admin permissions
  ADMIN_ALL = 'ADMIN_ALL',
  ADMIN_EDIT = 'ADMIN_EDIT',
}
