services:
  db:
    image: postgres:16
    container_name: companycrud_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U","app"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db: {}